export const folderCategories = [
  {
    key: 'api-routes',
    name: 'API Routes',
    icon: '🔌',
    description: 'REST API endpoints',
    required: true,
    structure: null, // Will be loaded from separate file
  },
  {
    key: 'database',
    name: 'Database',
    icon: '💾',
    description: 'Database connection & schemas',
    required: true,
  },
  {
    key: 'auth',
    name: 'Authentication',
    icon: '🔐',
    description: 'JWT, OAuth, sessions',
    required: false,
  },
  {
    key: 'services',
    name: 'Services',
    icon: '⚙️',
    description: 'Business logic services',
    required: true,
  },
  {
    key: 'middleware',
    name: 'Middleware',
    icon: '🛡️',
    description: 'Auth, validation, logging',
    required: false,
  },
  {
    key: 'cache',
    name: 'Caching',
    icon: '⚡',
    description: 'Redis/Memory cache',
    required: false,
  },
  {
    key: 'email',
    name: 'Email',
    icon: '📧',
    description: 'Email templates & sending',
    required: false,
  },
  {
    key: 'storage',
    name: 'File Storage',
    icon: '📁',
    description: 'S3, Cloudinary, local',
    required: false,
  },
  {
    key: 'payment',
    name: 'Payments',
    icon: '💳',
    description: 'Stripe, PayPal integration',
    required: false,
  },
  {
    key: 'queue',
    name: 'Job Queue',
    icon: '📬',
    description: 'Background jobs & workers',
    required: false,
  },
  {
    key: 'websocket',
    name: 'WebSocket',
    icon: '🔄',
    description: 'Real-time communication',
    required: false,
  },
  {
    key: 'logger',
    name: 'Logging',
    icon: '📝',
    description: 'Winston/Pino logging',
    required: false,
  },
  {
    key: 'monitoring',
    name: 'Monitoring',
    icon: '📊',
    description: 'Sentry, analytics',
    required: false,
  },
  {
    key: 'testing',
    name: 'Testing',
    icon: '🧪',
    description: 'Jest, Vitest setup',
    required: false,
  },
  {
    key: 'docker',
    name: 'Docker',
    icon: '🐳',
    description: 'Containerization files',
    required: false,
  },
  {
    key: 'graphql',
    name: 'GraphQL',
    icon: '🔷',
    description: 'GraphQL API setup',
    required: false,
  },
  {
    key: 'i18n',
    name: 'Internationalization',
    icon: '🌍',
    description: 'Multi-language support',
    required: false,
  },
  {
    key: 'security',
    name: 'Security',
    icon: '🔒',
    description: 'XSS, CSRF, rate limiting',
    required: false,
  },
];

export function getAllCategories() {
  return [
    {
      key: 'api-routes',
      name: 'API Routes',
      icon: '🔌',
      description: 'REST API endpoints with versioning',
      required: true,
      fileCount: 65,
      subFolders: [
        {
          key: 'auth',
          name: 'Authentication Routes',
          description: 'Login, register, password reset',
          required: true,
        },
        {
          key: 'users',
          name: 'User Routes',
          description: 'User CRUD operations',
          required: true,
        },
        {
          key: 'admin',
          name: 'Admin Routes',
          description: 'Admin panel endpoints',
          required: false,
        },
        {
          key: 'webhooks',
          name: 'Webhook Routes',
          description: 'Third-party webhooks',
          required: false,
        },
        {
          key: 'upload',
          name: 'File Upload Routes',
          description: 'File upload endpoints',
          required: false,
        },
        {
          key: 'payments',
          name: 'Payment Routes',
          description: 'Payment processing',
          required: false,
        },
      ],
    },
    {
      key: 'database',
      name: 'Database',
      icon: '💾',
      description: 'Database connection & schemas',
      required: true,
      fileCount: 10,
      subFolders: [
        {
          key: 'prisma',
          name: 'Prisma ORM',
          description: 'Prisma schema and migrations',
          required: false,
        },
        {
          key: 'drizzle',
          name: 'Drizzle ORM',
          description: 'Drizzle schema and config',
          required: false,
        },
      ],
    },
    {
      key: 'auth',
      name: 'Authentication',
      icon: '🔐',
      description: 'JWT, OAuth, sessions, 2FA',
      required: true,
      fileCount: 18,
      subFolders: [
        {
          key: 'jwt',
          name: 'JWT Authentication',
          description: 'JSON Web Token implementation',
          required: true,
        },
        {
          key: 'oauth',
          name: 'OAuth Providers',
          description: 'Google, GitHub, Facebook',
          required: false,
        },
        {
          key: 'session',
          name: 'Session Management',
          description: 'Session handling',
          required: false,
        },
        {
          key: 'guards',
          name: 'Auth Guards',
          description: 'Route protection guards',
          required: true,
        },
      ],
    },
    {
      key: 'services',
      name: 'Business Services',
      icon: '⚙️',
      description: 'Business logic services',
      required: true,
      fileCount: 9,
      subFolders: [],
    },
    {
      key: 'repositories',
      name: 'Data Repositories',
      icon: '📊',
      description: 'Data access layer',
      required: false,
      fileCount: 5,
      subFolders: [],
    },
    {
      key: 'middleware',
      name: 'Middleware',
      icon: '🛡️',
      description: 'Request/response middleware',
      required: true,
      fileCount: 12,
      subFolders: [],
    },
    {
      key: 'validators',
      name: 'Validators',
      icon: '✅',
      description: 'Request validation schemas',
      required: true,
      fileCount: 6,
      subFolders: [],
    },
    {
      key: 'cache',
      name: 'Caching',
      icon: '⚡',
      description: 'Redis/Memory cache',
      required: false,
      fileCount: 3,
      subFolders: [],
    },
    {
      key: 'queue',
      name: 'Job Queue',
      icon: '📬',
      description: 'Background jobs & workers',
      required: false,
      fileCount: 7,
      subFolders: [],
    },
    {
      key: 'email',
      name: 'Email Service',
      icon: '📧',
      description: 'Email templates & sending',
      required: false,
      fileCount: 9,
      subFolders: [],
    },
    {
      key: 'storage',
      name: 'File Storage',
      icon: '📁',
      description: 'S3, Cloudinary, local storage',
      required: false,
      fileCount: 6,
      subFolders: [],
    },
    {
      key: 'payment',
      name: 'Payments',
      icon: '💳',
      description: 'Stripe, PayPal integration',
      required: false,
      fileCount: 3,
      subFolders: [],
    },
    {
      key: 'websocket',
      name: 'WebSocket',
      icon: '🔄',
      description: 'Real-time communication',
      required: false,
      fileCount: 3,
      subFolders: [],
    },
    {
      key: 'logger',
      name: 'Logging',
      icon: '📝',
      description: 'Winston/Pino logging',
      required: false,
      fileCount: 4,
      subFolders: [],
    },
    {
      key: 'monitoring',
      name: 'Monitoring',
      icon: '📊',
      description: 'Sentry, Datadog, NewRelic',
      required: false,
      fileCount: 3,
      subFolders: [],
    },
    {
      key: 'security',
      name: 'Security',
      icon: '🔒',
      description: 'XSS, CSRF, rate limiting',
      required: true,
      fileCount: 4,
      subFolders: [],
    },
    {
      key: 'testing',
      name: 'Testing',
      icon: '🧪',
      description: 'Jest, Vitest, Playwright',
      required: false,
      fileCount: 15,
      subFolders: [],
    },
    {
      key: 'docker',
      name: 'Docker',
      icon: '🐳',
      description: 'Containerization files',
      required: false,
      fileCount: 4,
      subFolders: [],
    },
    {
      key: 'graphql',
      name: 'GraphQL',
      icon: '🔷',
      description: 'GraphQL API setup',
      required: false,
      fileCount: 10,
      subFolders: [],
    },
    {
      key: 'i18n',
      name: 'Internationalization',
      icon: '🌍',
      description: 'Multi-language support',
      required: false,
      fileCount: 12,
      subFolders: [],
    },
    {
      key: 'types',
      name: 'TypeScript Types',
      icon: '📘',
      description: 'Type definitions',
      required: true,
      fileCount: 11,
      subFolders: [],
    },
    {
      key: 'constants',
      name: 'Constants',
      icon: '📌',
      description: 'Application constants',
      required: true,
      fileCount: 7,
      subFolders: [],
    },
    {
      key: 'utils',
      name: 'Utilities',
      icon: '🔧',
      description: 'Helper functions',
      required: true,
      fileCount: 9,
      subFolders: [],
    },
    {
      key: 'dto',
      name: 'Data Transfer Objects',
      icon: '📦',
      description: 'Request/response DTOs',
      required: false,
      fileCount: 9,
      subFolders: [],
    },
    {
      key: 'exceptions',
      name: 'Exceptions',
      icon: '⚠️',
      description: 'Custom error classes',
      required: true,
      fileCount: 6,
      subFolders: [],
    },
    {
      key: 'jobs',
      name: 'Scheduled Jobs',
      icon: '⏰',
      description: 'Cron jobs & schedulers',
      required: false,
      fileCount: 7,
      subFolders: [],
    },
    {
      key: 'events',
      name: 'Event System',
      icon: '📡',
      description: 'Event emitters & listeners',
      required: false,
      fileCount: 6,
      subFolders: [],
    },
    {
      key: 'config',
      name: 'Configuration',
      icon: '⚙️',
      description: 'App configuration files',
      required: true,
      fileCount: 10,
      subFolders: [],
    },
  ];
}