
import { LEVELS } from './levels.js';

export const folderCategories = [
  // ===== BEGINNER LEVEL (50 categories) =====
  {
    key: 'api',
    name: 'API Routes',
    icon: '🔌',
    description: 'REST API endpoints',
    required: true,
    fileCount: 1,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'app',
    name: 'App Directory',
    icon: '📱',
    description: 'Next.js app directory',
    required: true,
    fileCount: 1,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'config',
    name: 'Configuration',
    icon: '⚙️',
    description: 'App configuration',
    required: true,
    fileCount: 1,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'constants',
    name: 'Constants',
    icon: '📌',
    description: 'Application constants',
    required: true,
    fileCount: 1,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'database',
    name: 'Database',
    icon: '💾',
    description: 'Database connections (MongoDB, PostgreSQL, MySQL, etc.)',
    required: true,
    fileCount: 10,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'docs',
    name: 'Documentation',
    icon: '📚',
    description: 'API documentation',
    required: false,
    fileCount: 1,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'exceptions',
    name: 'Exceptions',
    icon: '⚠️',
    description: 'Error handling',
    required: true,
    fileCount: 1,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'helpers',
    name: 'Helpers',
    icon: '🔧',
    description: 'Helper functions',
    required: true,
    fileCount: 1,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'lib',
    name: 'Library',
    icon: '📚',
    description: 'Core library functions',
    required: true,
    fileCount: 1,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'middleware',
    name: 'Middleware',
    icon: '🛡️',
    description: 'Request middleware',
    required: true,
    fileCount: 1,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'public',
    name: 'Public Assets',
    icon: '🌐',
    description: 'Static files',
    required: true,
    fileCount: 1,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'root',
    name: 'Root Files',
    icon: '📄',
    description: 'Root configuration files',
    required: true,
    fileCount: 1,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'types',
    name: 'TypeScript Types',
    icon: '📘',
    description: 'Type definitions',
    required: true,
    fileCount: 1,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'validators',
    name: 'Validators',
    icon: '✅',
    description: 'Input validation',
    required: true,
    fileCount: 1,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'api-docs',
    name: 'API Documentation',
    icon: '📖',
    description: 'Swagger/OpenAPI/AsyncAPI documentation',
    required: false,
    fileCount: 7,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'caching',
    name: 'Caching',
    icon: '⚡',
    description: 'Redis, Memcached, CDN, Edge caching',
    required: false,
    fileCount: 7,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'calendar',
    name: 'Calendar',
    icon: '📅',
    description: 'Google Calendar, Calendly, scheduling',
    required: false,
    fileCount: 7,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'cms',
    name: 'CMS Integration',
    icon: '📝',
    description: 'Contentful, Strapi, Sanity, WordPress',
    required: false,
    fileCount: 9,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'compression',
    name: 'Compression',
    icon: '🗜️',
    description: 'Gzip, Brotli, image/video compression',
    required: false,
    fileCount: 6,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'crm',
    name: 'CRM Integration',
    icon: '📊',
    description: 'Salesforce, HubSpot, Zoho',
    required: false,
    fileCount: 6,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'currency',
    name: 'Currency',
    icon: '💱',
    description: 'Exchange rates, crypto conversion, formatting',
    required: false,
    fileCount: 5,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'custom-middleware',
    name: 'Custom Middleware',
    icon: '🎛️',
    description: 'CORS, Helmet, compression, cookies',
    required: false,
    fileCount: 8,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'data-transfer',
    name: 'Data Transfer',
    icon: '📤',
    description: 'Import/Export CSV, JSON, XML, bulk operations',
    required: false,
    fileCount: 6,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'feedback',
    name: 'Feedback System',
    icon: '💬',
    description: 'User feedback, bug reports, NPS, surveys',
    required: false,
    fileCount: 5,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'file-formats',
    name: 'File Formats',
    icon: '📋',
    description: 'CSV, Excel, PDF, JSON, XML, YAML parsers',
    required: false,
    fileCount: 7,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'graceful-shutdown',
    name: 'Graceful Shutdown',
    icon: '🛑',
    description: 'Clean server shutdown, connection draining',
    required: false,
    fileCount: 5,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'health-checks',
    name: 'Health Checks',
    icon: '❤️',
    description: 'Liveness, readiness, dependency checks',
    required: false,
    fileCount: 7,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'invoicing',
    name: 'Invoicing',
    icon: '🧾',
    description: 'Invoice generation, PDF, recurring, tax calculation',
    required: false,
    fileCount: 6,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'language-detection',
    name: 'Language Detection',
    icon: '🔍',
    description: 'Auto language detection, browser/IP-based',
    required: false,
    fileCount: 5,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'licensing',
    name: 'Licensing',
    icon: '🔑',
    description: 'License generation, activation, validation',
    required: false,
    fileCount: 6,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'media',
    name: 'Media Processing',
    icon: '🎬',
    description: 'Image resize, video transcode, thumbnails, watermarks',
    required: false,
    fileCount: 9,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'notifications',
    name: 'Notifications',
    icon: '🔔',
    description: 'Email, SMS, Push, In-app, Webhooks',
    required: false,
    fileCount: 10,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'onboarding',
    name: 'User Onboarding',
    icon: '🚀',
    description: 'Product tours, checklists, activation',
    required: false,
    fileCount: 5,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'payments',
    name: 'Payment Gateways',
    icon: '💳',
    description: 'Stripe, PayPal, Razorpay, crypto payments',
    required: false,
    fileCount: 11,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'referrals',
    name: 'Referral System',
    icon: '🎁',
    description: 'Invite system, tracking, rewards, viral loops',
    required: false,
    fileCount: 5,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'regional',
    name: 'Regional Settings',
    icon: '🗺️',
    description: 'Address, date, number, phone formats',
    required: false,
    fileCount: 5,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'reports',
    name: 'Reporting',
    icon: '📈',
    description: 'Dashboard, charts, PDF/Excel reports, scheduling',
    required: false,
    fileCount: 6,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'sanitization',
    name: 'Sanitization',
    icon: '🧹',
    description: 'HTML, SQL, URL, filename sanitization',
    required: false,
    fileCount: 6,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'search',
    name: 'Search Engines',
    icon: '🔍',
    description: 'Elasticsearch, Algolia, Meilisearch, Typesense',
    required: false,
    fileCount: 8,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'smoke-testing',
    name: 'Smoke Testing',
    icon: '🧪',
    description: 'Critical paths, sanity checks, health endpoints',
    required: false,
    fileCount: 4,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'subscriptions',
    name: 'Subscriptions',
    icon: '💳',
    description: 'Plans, billing, trials, upgrades, proration',
    required: false,
    fileCount: 7,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'support',
    name: 'Support System',
    icon: '🎧',
    description: 'Zendesk, Intercom, Freshdesk, HelpScout',
    required: false,
    fileCount: 6,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'teams',
    name: 'Team Management',
    icon: '👥',
    description: 'Workspaces, roles, invitations, permissions',
    required: false,
    fileCount: 6,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'timezone',
    name: 'Timezone',
    icon: '🌍',
    description: 'Conversion, DST, scheduling, user timezone',
    required: false,
    fileCount: 5,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'validation',
    name: 'Validation Schemas',
    icon: '✔️',
    description: 'Zod, Yup, Joi, Class Validator, AJV',
    required: false,
    fileCount: 6,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'api-versioning',
    name: 'API Versioning',
    icon: '🔢',
    description: 'URL, header, content-type versioning, deprecation',
    required: false,
    fileCount: 7,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'email-marketing',
    name: 'Email Marketing',
    icon: '📧',
    description: 'Mailchimp, SendGrid, Klaviyo campaigns',
    required: false,
    fileCount: 7,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'sms-marketing',
    name: 'SMS Marketing',
    icon: '📱',
    description: 'Twilio, Nexmo campaigns',
    required: false,
    fileCount: 5,
    level: LEVELS.BEGINNER,
  },
  {
    key: 'push-campaigns',
    name: 'Push Campaigns',
    icon: '🔔',
    description: 'OneSignal, Airship, batch push notifications',
    required: false,
    fileCount: 5,
    level: LEVELS.BEGINNER,
  },

  // ===== INTERMEDIATE LEVEL (150 categories) =====
  {
    key: 'services',
    name: 'Business Services',
    icon: '⚙️',
    description: 'Business logic layer',
    required: true,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'repositories',
    name: 'Repositories',
    icon: '📊',
    description: 'Data access layer',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'providers',
    name: 'Providers',
    icon: '🔌',
    description: 'Service providers',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'decorators',
    name: 'Decorators',
    icon: '🎨',
    description: 'Custom decorators',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'filters',
    name: 'Filters',
    icon: '🔧',
    description: 'Request filters',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'interceptors',
    name: 'Interceptors',
    icon: '🔀',
    description: 'Request interceptors',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'hooks',
    name: 'Hooks',
    icon: '🪝',
    description: 'Lifecycle hooks',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'events',
    name: 'Event System',
    icon: '📡',
    description: 'Event handling',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'jobs',
    name: 'Scheduled Jobs',
    icon: '⏰',
    description: 'Background jobs',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'schemas',
    name: 'Schemas',
    icon: '📋',
    description: 'Data schemas',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'dto',
    name: 'DTOs',
    icon: '📦',
    description: 'Data transfer objects',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'policies',
    name: 'Policies',
    icon: '🛡️',
    description: 'Authorization policies',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'scripts',
    name: 'Scripts',
    icon: '📜',
    description: 'Utility scripts',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'tests',
    name: 'Testing',
    icon: '🧪',
    description: 'Test suites',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'locales',
    name: 'Locales',
    icon: '🌍',
    description: 'Translations',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'drizzle',
    name: 'Drizzle ORM',
    icon: '🗄️',
    description: 'Drizzle database ORM',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'prisma',
    name: 'Prisma ORM',
    icon: '💾',
    description: 'Prisma database ORM',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'graphql',
    name: 'GraphQL',
    icon: '🔷',
    description: 'GraphQL API',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'docker',
    name: 'Docker',
    icon: '🐳',
    description: 'Containerization',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'github',
    name: 'GitHub Actions',
    icon: '⚙️',
    description: 'CI/CD workflows',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'husky',
    name: 'Husky',
    icon: '🐶',
    description: 'Git hooks',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'vscode',
    name: 'VS Code',
    icon: '💻',
    description: 'VS Code settings',
    required: false,
    fileCount: 1,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'api-clients',
    name: 'API Clients',
    icon: '🔌',
    description: 'AWS S3, Cloudinary, Google Maps, HubSpot, OpenAI, Stripe, Twilio',
    required: false,
    fileCount: 11,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'auth-providers',
    name: 'Auth Providers',
    icon: '🔑',
    description: 'Google, Facebook, GitHub, Apple, Discord OAuth',
    required: false,
    fileCount: 10,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'auth-strategies',
    name: 'Auth Strategies',
    icon: '🔐',
    description: 'JWT, OAuth2, SAML, WebAuthn, Passkey, OTP, Magic Link',
    required: false,
    fileCount: 11,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'analytics',
    name: 'Analytics',
    icon: '📊',
    description: 'Google Analytics, Mixpanel, Amplitude, PostHog, Segment',
    required: false,
    fileCount: 9,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'realtime',
    name: 'Real-time',
    icon: '🔄',
    description: 'Socket.io, Pusher, Ably, Firebase RTDB, WebSockets',
    required: false,
    fileCount: 9,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'background-jobs',
    name: 'Background Jobs',
    icon: '📬',
    description: 'BullMQ, Agenda, Inngest, Quirrel, PG Boss',
    required: false,
    fileCount: 8,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'geolocation',
    name: 'Geolocation',
    icon: '📍',
    description: 'Google Maps, Mapbox, HERE, MaxMind, IPStack',
    required: false,
    fileCount: 7,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'communication',
    name: 'Communication',
    icon: '💬',
    description: 'Twilio video/voice, Sendbird, Stream Chat, Agora, Zoom API',
    required: false,
    fileCount: 7,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'social-media',
    name: 'Social Media',
    icon: '📱',
    description: 'Facebook, Instagram, Twitter, LinkedIn, TikTok, YouTube APIs',
    required: false,
    fileCount: 8,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'rate-limiting',
    name: 'Rate Limiting',
    icon: '⏱️',
    description: 'Token bucket, sliding window, leaky bucket, Redis',
    required: false,
    fileCount: 7,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'security',
    name: 'Security',
    icon: '🔒',
    description: 'XSS, CSRF, SQL injection, DDoS, encryption, hashing',
    required: false,
    fileCount: 10,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'error-tracking',
    name: 'Error Tracking',
    icon: '🐛',
    description: 'Sentry, Rollbar, Bugsnag, LogRocket, Airbrake',
    required: false,
    fileCount: 7,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'feature-flags',
    name: 'Feature Flags',
    icon: '🚩',
    description: 'LaunchDarkly, Split, Flagsmith, Unleash, ConfigCat',
    required: false,
    fileCount: 7,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'ab-testing',
    name: 'A/B Testing',
    icon: '🔬',
    description: 'Optimizely, Split, Growthbook, Statsig, LaunchDarkly',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'load-balancing',
    name: 'Load Balancing',
    icon: '⚖️',
    description: 'Round robin, least connections, IP hash, weighted, sticky sessions',
    required: false,
    fileCount: 7,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'api-tracking',
    name: 'API Tracking',
    icon: '📈',
    description: 'Usage metrics, quota management, billing, throttling',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'api-keys',
    name: 'API Keys',
    icon: '🔑',
    description: 'Generation, hashing, rotation, revocation, scopes',
    required: false,
    fileCount: 7,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'audit-logging',
    name: 'Audit Logging',
    icon: '📝',
    description: 'Access logs, action logs, change tracking, event sourcing',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'data-masking',
    name: 'Data Masking',
    icon: '🎭',
    description: 'PII protection, email/phone/credit card masking',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'ip-control',
    name: 'IP Control',
    icon: '🌐',
    description: 'Whitelist, blacklist, geo-blocking, IP reputation',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'password-policies',
    name: 'Password Policies',
    icon: '🔐',
    description: 'Complexity rules, expiration, history, breach detection',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'bot-protection',
    name: 'Bot Protection',
    icon: '🤖',
    description: 'reCAPTCHA, hCaptcha, Cloudflare Turnstile, fingerprinting',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'compliance',
    name: 'Compliance',
    icon: '⚖️',
    description: 'GDPR, CCPA, HIPAA, PCI-DSS, SOX data retention',
    required: false,
    fileCount: 7,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'data-privacy',
    name: 'Data Privacy',
    icon: '🔏',
    description: 'Consent management, cookie consent, right to be forgotten',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'data-retention',
    name: 'Data Retention',
    icon: '🗄️',
    description: 'Retention policies, archival, deletion scheduling',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'multi-tenancy',
    name: 'Multi-Tenancy',
    icon: '🏢',
    description: 'Shared/separate schema, tenant isolation, routing',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'api-mocking',
    name: 'API Mocking',
    icon: '🎭',
    description: 'Mock server, faker data, response templates',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'load-testing',
    name: 'Load Testing',
    icon: '⚡',
    description: 'k6, Artillery, JMeter, Gatling',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'contract-testing',
    name: 'Contract Testing',
    icon: '📜',
    description: 'Pact, API contracts, schema validation',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'video-processing',
    name: 'Video Processing',
    icon: '🎥',
    description: 'FFmpeg, transcoding, streaming, subtitles, thumbnails',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'audio-processing',
    name: 'Audio Processing',
    icon: '🎵',
    description: 'Format conversion, noise reduction, mixing, transcription',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'image-recognition',
    name: 'Image Recognition',
    icon: '👁️',
    description: 'AWS Rekognition, Google Vision, Clarifai, custom models',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'ocr',
    name: 'OCR',
    icon: '📝',
    description: 'Tesseract, Google Cloud Vision, Azure OCR, Textract',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'content-moderation',
    name: 'Content Moderation',
    icon: '🚫',
    description: 'AI moderation, image/text/video filtering',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'translation',
    name: 'Translation',
    icon: '🌐',
    description: 'Google Translate, DeepL, Crowdin, Lokalise',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'leaderboards',
    name: 'Leaderboards',
    icon: '🏆',
    description: 'Real-time scores, Redis leaderboard, seasonal, tournaments',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'achievements',
    name: 'Achievements',
    icon: '🎖️',
    description: 'Badge system, points, progression, rewards',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'matchmaking',
    name: 'Matchmaking',
    icon: '🎮',
    description: 'Skill-based, Elo rating, queue system, team formation',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'live-streaming',
    name: 'Live Streaming',
    icon: '📡',
    description: 'HLS, RTMP, WebRTC, DASH streaming',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'iap',
    name: 'In-App Purchases',
    icon: '💰',
    description: 'Apple IAP, Google Play, receipt validation, subscriptions',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'affiliates',
    name: 'Affiliate Program',
    icon: '🤝',
    description: 'Commissions, tracking, payouts, referral links',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'loyalty',
    name: 'Loyalty Program',
    icon: '💎',
    description: 'Points system, tiers, rewards catalog, gamification',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'contests',
    name: 'Contests',
    icon: '🎉',
    description: 'Sweepstakes, voting system, random winner, viral loops',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'personalization',
    name: 'Personalization',
    icon: '👤',
    description: 'User segmentation, dynamic content, behavioral targeting, A/B testing',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'customer-journey',
    name: 'Customer Journey',
    icon: '🗺️',
    description: 'Journey builder, touchpoint tracking, attribution, conversion funnel',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'retargeting',
    name: 'Retargeting',
    icon: '🎯',
    description: 'Facebook/Google retargeting, pixel tracking, dynamic ads',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'cro',
    name: 'CRO',
    icon: '📈',
    description: 'Conversion optimization, heatmaps, session recording, exit intent',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'bi-tools',
    name: 'BI Tools',
    icon: '📊',
    description: 'Tableau, PowerBI, Looker, Metabase, Superset',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'data-aggregation',
    name: 'Data Aggregation',
    icon: '📉',
    description: 'Grouping, map-reduce, rollup, cube, pivoting',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'timeseries-db',
    name: 'Time Series DB',
    icon: '⏰',
    description: 'InfluxDB, TimescaleDB, Prometheus, QuestDB, Graphite',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'cdp',
    name: 'CDP',
    icon: '👥',
    description: 'Segment, Rudderstack, mParticle, Customer 360',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'etl',
    name: 'ETL',
    icon: '🔄',
    description: 'Extract, Transform, Load, Airflow, Dagster, Prefect',
    required: false,
    fileCount: 7,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'chatbots',
    name: 'Chatbots',
    icon: '🤖',
    description: 'Dialogflow, Lex, Rasa, Watson, Botpress, intent recognition',
    required: false,
    fileCount: 9,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'nlp',
    name: 'NLP',
    icon: '🧠',
    description: 'SpaCy, NLTK, sentiment analysis, entity extraction, topic modeling',
    required: false,
    fileCount: 9,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'recommendations',
    name: 'Recommendations',
    icon: '💡',
    description: 'Collaborative filtering, content-based, hybrid, matrix factorization',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'speech',
    name: 'Speech Recognition',
    icon: '🎤',
    description: 'AWS Transcribe, Google Speech, Azure Speech, Whisper AI, Deepgram',
    required: false,
    fileCount: 7,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'tts',
    name: 'Text-to-Speech',
    icon: '🔊',
    description: 'Amazon Polly, Google TTS, Azure Speech, ElevenLabs, voice cloning',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'influencer',
    name: 'Influencer Marketing',
    icon: '⭐',
    description: 'Discovery, collaboration, campaign tracking, ROI measurement',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'config-management',
    name: 'Config Management',
    icon: '⚙️',
    description: 'AWS Secrets, Vault, Azure KeyVault, Consul, dotenv',
    required: false,
    fileCount: 7,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'secrets-rotation',
    name: 'Secrets Rotation',
    icon: '🔄',
    description: 'Auto-rotation, AWS/Vault rotation',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'deployment-strategies',
    name: 'Deployment',
    icon: '🚀',
    description: 'Blue-green, canary, rolling update, feature toggle deploy',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'auto-scaling',
    name: 'Auto-Scaling',
    icon: '📈',
    description: 'Horizontal/vertical scaling, predictive, schedule-based',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'networking',
    name: 'Networking',
    icon: '🌐',
    description: 'VPC, security groups, ACLs, service mesh',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'cost-optimization',
    name: 'Cost Optimization',
    icon: '💰',
    description: 'Cost alerts, reserved instances, spot instances, resource tagging',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'acl',
    name: 'ACL',
    icon: '🔒',
    description: 'Role-based, attribute-based, resource-based, policy-based access control',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'compliance-reporting',
    name: 'Compliance Reporting',
    icon: '📋',
    description: 'GDPR, ISO 27001, SOX compliance, audit trails',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'vulnerability-scanning',
    name: 'Vulnerability Scanning',
    icon: '🔍',
    description: 'Code scanning, dependency check, container/infrastructure scanning',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'incident-response',
    name: 'Incident Response',
    icon: '🚨',
    description: 'Detection, containment, remediation, post-mortem',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'drm',
    name: 'DRM',
    icon: '🔐',
    description: 'Content encryption, license verification, watermarking',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'ediscovery',
    name: 'eDiscovery',
    icon: '🔎',
    description: 'Data collection, preservation, search, export',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'serverless',
    name: 'Serverless',
    icon: '☁️',
    description: 'AWS Lambda, Azure Functions, Google Cloud Functions, Vercel/Netlify',
    required: false,
    fileCount: 7,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'devops',
    name: 'DevOps',
    icon: '⚙️',
    description: 'CI/CD, Ansible, Terraform, Kubernetes, deployment, monitoring',
    required: false,
    fileCount: 9,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'waf',
    name: 'WAF',
    icon: '🛡️',
    description: 'AWS WAF, Cloudflare WAF, Imperva, ModSecurity',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'web3',
    name: 'Web3',
    icon: '⛓️',
    description: 'Ethereum, Polygon, Solana, NFTs, MetaMask, WalletConnect',
    required: false,
    fileCount: 10,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'healthcare',
    name: 'Healthcare',
    icon: '🏥',
    description: 'FHIR, HL7, HIPAA, patient records, telemedicine',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'fintech',
    name: 'FinTech',
    icon: '💳',
    description: 'KYC, AML, open banking, Plaid, PSD2 compliance',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'elearning',
    name: 'E-Learning',
    icon: '📚',
    description: 'Course management, quizzes, certificates, progress tracking, SCORM',
    required: false,
    fileCount: 6,
    level: LEVELS.INTERMEDIATE,
  },

  // Continue adding remaining intermediate categories...
  {
    key: 'content-moderation-ai',
    name: 'Content Moderation AI',
    icon: '🚫',
    description: 'NSFW detection, hate speech, copyright detection',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'content-recommendation',
    name: 'Content Recommendation',
    icon: '💡',
    description: 'Collaborative/content-based filtering, hybrid recommender',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'vod',
    name: 'Video on Demand',
    icon: '🎬',
    description: 'Adaptive streaming, subtitles, watch history',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'podcast',
    name: 'Podcast',
    icon: '🎙️',
    description: 'RSS feed, distribution, analytics',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'music-streaming',
    name: 'Music Streaming',
    icon: '🎵',
    description: 'Audio fingerprinting, playlists, royalty calculation',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'subtitle-generation',
    name: 'Subtitle Generation',
    icon: '📝',
    description: 'Speech-to-text, translation, synchronization',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'live-broadcasting',
    name: 'Live Broadcasting',
    icon: '📡',
    description: 'Transcoding, CDN distribution, interactive features',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'virtual-events',
    name: 'Virtual Events',
    icon: '🎪',
    description: 'Session management, networking, virtual booths',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'stock-media',
    name: 'Stock Media',
    icon: '📸',
    description: 'Search optimization, contributor management, royalty distribution',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'print-on-demand',
    name: 'Print on Demand',
    icon: '🖨️',
    description: 'Product customization, print file generation, fulfillment',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'dam',
    name: 'Digital Asset Management',
    icon: '🗂️',
    description: 'Asset library, metadata, version control',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'brand-assets',
    name: 'Brand Assets',
    icon: '🎨',
    description: 'Logo variations, brand guidelines, template library',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'color-palette',
    name: 'Color Palette',
    icon: '🎨',
    description: 'Palette extraction, color harmony, accessibility checker',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'font-management',
    name: 'Font Management',
    icon: '🔤',
    description: 'Font library, licensing tracking, web font serving',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'design-versioning',
    name: 'Design Versioning',
    icon: '📐',
    description: 'Design history, branch management, merge conflicts',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'creative-workflow',
    name: 'Creative Workflow',
    icon: '🎨',
    description: 'Approval process, deadline tracking, asset distribution',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'creative-briefs',
    name: 'Creative Briefs',
    icon: '📋',
    description: 'Brief creation, project kickoff, stakeholder approval',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: '3d-models',
    name: '3D Models',
    icon: '🎲',
    description: 'Model rendering, texture management, format conversion',
    required: false,
    fileCount: 4,
    level: LEVELS.INTERMEDIATE,
  },
  {
    key: 'ar-vr',
    name: 'AR/VR',
    icon: '🥽',
    description: 'ARKit, ARCore, WebXR, spatial anchors',
    required: false,
    fileCount: 5,
    level: LEVELS.INTERMEDIATE,
  },

  // ===== ADVANCED LEVEL (100 categories) =====
  {
    key: 'ai-ml',
    name: 'AI/ML Services',
    icon: '🤖',
    description: 'OpenAI, Anthropic, TensorFlow, HuggingFace, Langchain, Pinecone',
    required: false,
    fileCount: 10,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'ai-agents',
    name: 'AI Agents',
    icon: '🧠',
    description: 'Autonomous agents, Langchain agents, AutoGPT, tool calling, memory',
    required: false,
    fileCount: 6,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'vector-db',
    name: 'Vector Databases',
    icon: '🔢',
    description: 'Pinecone, Weaviate, Qdrant, Milvus, Chroma, FAISS',
    required: false,
    fileCount: 7,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'mlops',
    name: 'MLOps',
    icon: '🔬',
    description: 'Model training, deployment, monitoring, experiment tracking, feature store',
    required: false,
    fileCount: 7,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'computer-vision',
    name: 'Computer Vision',
    icon: '👁️',
    description: 'Object detection, face recognition, pose estimation, OpenCV, scene understanding',
    required: false,
    fileCount: 7,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'predictive-analytics',
    name: 'Predictive Analytics',
    icon: '🔮',
    description: 'Time series forecast, churn prediction, classification, regression, anomaly detection',
    required: false,
    fileCount: 6,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'workflow-automation',
    name: 'Workflow Automation',
    icon: '⚡',
    description: 'n8n, Airflow workflows, Step Functions, Temporal, Zapier-like',
    required: false,
    fileCount: 6,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'rpa',
    name: 'RPA',
    icon: '🤖',
    description: 'Selenium, Puppeteer, Playwright automation, UI automation',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'rules-engine',
    name: 'Rules Engine',
    icon: '⚙️',
    description: 'Business rules, decision tables, Drools, JSON rules',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'microservices',
    name: 'Microservices',
    icon: '🔷',
    description: 'Service mesh, API gateway, circuit breaker, service discovery, load balancer',
    required: false,
    fileCount: 7,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'data-pipeline',
    name: 'Data Pipeline',
    icon: '🚰',
    description: 'Batch/stream processing, ETL, data transformation, Kafka, RabbitMQ',
    required: false,
    fileCount: 7,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'message-queues',
    name: 'Message Queues',
    icon: '📬',
    description: 'Kafka, RabbitMQ, SQS, NATS, Google Pub/Sub, Azure Service Bus',
    required: false,
    fileCount: 9,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'circuit-breakers',
    name: 'Circuit Breakers',
    icon: '🔌',
    description: 'Opossum, Hystrix, Cockatiel, Resilience4j, Brakes',
    required: false,
    fileCount: 6,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'service-discovery',
    name: 'Service Discovery',
    icon: '🔍',
    description: 'Consul, Eureka, etcd, Zookeeper, Nacos',
    required: false,
    fileCount: 6,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'throttling',
    name: 'Throttling',
    icon: '🚦',
    description: 'Adaptive throttle, token bucket, sliding window, concurrent requests',
    required: false,
    fileCount: 6,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'distributed-tracing',
    name: 'Distributed Tracing',
    icon: '🔗',
    description: 'Jaeger, Zipkin, OpenTelemetry, AWS X-Ray, Datadog APM, New Relic',
    required: false,
    fileCount: 7,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'observability',
    name: 'Observability',
    icon: '👁️',
    description: 'Metrics, log aggregation, distributed tracing, alerting',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'chaos-testing',
    name: 'Chaos Testing',
    icon: '💥',
    description: 'Chaos Monkey, CPU/memory stress, network chaos',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'chaos-engineering',
    name: 'Chaos Engineering',
    icon: '⚡',
    description: 'Chaos Mesh, fault/latency injection, failure scenarios',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'iac',
    name: 'Infrastructure as Code',
    icon: '🏗️',
    description: 'Terraform modules, CloudFormation, CDK, Pulumi',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'orchestration',
    name: 'Orchestration',
    icon: '🎼',
    description: 'Kubernetes manifests, Helm charts, Docker Swarm, Nomad',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'disaster-recovery',
    name: 'Disaster Recovery',
    icon: '🆘',
    description: 'Backup strategies, failover, point-in-time recovery, RTO/RPO',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'data-warehouse',
    name: 'Data Warehouse',
    icon: '🏢',
    description: 'Snowflake, BigQuery, Redshift, Databricks, ClickHouse',
    required: false,
    fileCount: 6,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'event-streaming',
    name: 'Event Streaming',
    icon: '🌊',
    description: 'Kafka Streams, Flink, Kinesis, Spark Streaming',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'data-lakes',
    name: 'Data Lakes',
    icon: '🏞️',
    description: 'AWS S3 Lake, Azure Data Lake, Delta Lake, Iceberg',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'stream-processing',
    name: 'Stream Processing',
    icon: '🌊',
    description: 'Apache Flink, Kafka Streams, Spark Streaming, Pulsar',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'cep',
    name: 'Complex Event Processing',
    icon: '🔄',
    description: 'Event correlation, pattern matching, temporal queries',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'deduplication',
    name: 'Deduplication',
    icon: '🔍',
    description: 'Hash-based, fuzzy matching, ML dedup',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'data-quality',
    name: 'Data Quality',
    icon: '✅',
    description: 'Profiling, validation rules, cleansing',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'data-catalog',
    name: 'Data Catalog',
    icon: '📖',
    description: 'Data discovery, lineage tracking, metadata management',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'mdm',
    name: 'Master Data Management',
    icon: '👑',
    description: 'Golden records, data matching, hierarchy management',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'data-virtualization',
    name: 'Data Virtualization',
    icon: '🌐',
    description: 'Federated queries, view creation, caching strategy',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'cdc',
    name: 'Change Data Capture',
    icon: '🔄',
    description: 'Change tracking, Debezium, event sourcing',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'anonymization',
    name: 'Anonymization',
    icon: '🎭',
    description: 'Data masking, differential privacy, k-anonymity',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'synthetic-data',
    name: 'Synthetic Data',
    icon: '🔬',
    description: 'Faker advanced, ML generation, schema-aware',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'oauth-sso',
    name: 'OAuth/SSO',
    icon: '🔐',
    description: 'OAuth2 server, OpenID Connect, SAML2, LDAP, Active Directory, CAS',
    required: false,
    fileCount: 7,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'security-testing',
    name: 'Security Testing',
    icon: '🛡️',
    description: 'Penetration test, authentication test, CSRF/XSS/SQL injection test',
    required: false,
    fileCount: 6,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'dlp',
    name: 'Data Loss Prevention',
    icon: '🔒',
    description: 'Data classification, sensitive data detection, policy enforcement',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'identity-governance',
    name: 'Identity Governance',
    icon: '👤',
    description: 'User provisioning, access reviews, segregation of duties',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'zero-trust',
    name: 'Zero Trust',
    icon: '🔐',
    description: 'Identity verification, least privilege, micro-segmentation',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'behavioral-analytics',
    name: 'Behavioral Analytics',
    icon: '📊',
    description: 'User behavior analysis, anomaly detection, threat detection',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'honeypots',
    name: 'Honeypots',
    icon: '🍯',
    description: 'Decoy systems, intrusion detection, threat intelligence',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'security-automation',
    name: 'Security Automation',
    icon: '🤖',
    description: 'Auto-remediation, incident automation, security orchestration',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'credential-stuffing',
    name: 'Credential Stuffing Protection',
    icon: '🛡️',
    description: 'Bot detection, device fingerprinting, velocity checks',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'secrets-advanced',
    name: 'Advanced Secrets',
    icon: '🔐',
    description: 'Dynamic secrets, secret injection, secret scanning',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'hsm',
    name: 'HSM',
    icon: '🔒',
    description: 'Hardware security module, encryption operations, key management, signing',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'blockchain-security',
    name: 'Blockchain Security',
    icon: '⛓️',
    description: 'Consensus verification, private key management, transaction validation',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'api-security-testing',
    name: 'API Security Testing',
    icon: '🔒',
    description: 'Authentication testing, fuzzing, injection testing',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'rasp',
    name: 'RASP',
    icon: '🛡️',
    description: 'Runtime protection, attack detection, automated blocking',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'graphql-federation',
    name: 'GraphQL Federation',
    icon: '🔷',
    description: 'Gateway, subgraph, schema stitching',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'grpc',
    name: 'gRPC',
    icon: '⚡',
    description: 'Client, server, proto definitions, streaming',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'websockets-advanced',
    name: 'WebSockets Advanced',
    icon: '🔄',
    description: 'Broadcast, room management, presence, reconnection',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'sse',
    name: 'Server-Sent Events',
    icon: '📡',
    description: 'Event stream, heartbeat, reconnection',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'long-polling',
    name: 'Long Polling',
    icon: '🔄',
    description: 'Polling strategy, timeout handling',
    required: false,
    fileCount: 3,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'webhook-management',
    name: 'Webhook Management',
    icon: '🔗',
    description: 'Registration, delivery tracking, retry logic, signature verification',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'api-gateway',
    name: 'API Gateway',
    icon: '🚪',
    description: 'Routing, aggregation, rate limiting, transformation',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'bff',
    name: 'Backend for Frontend',
    icon: '🎨',
    description: 'Web BFF, mobile BFF, desktop BFF',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'api-composition',
    name: 'API Composition',
    icon: '🧩',
    description: 'Parallel calls, sequential calls, fallback strategies',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'api-transformation',
    name: 'API Transformation',
    icon: '🔄',
    description: 'Format transformation, protocol conversion, legacy API wrapper',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'real-estate',
    name: 'Real Estate',
    icon: '🏠',
    description: 'Property listings, booking system, virtual tours, mortgage calculator',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'food-delivery',
    name: 'Food Delivery',
    icon: '🍕',
    description: 'Driver assignment, order tracking, route optimization, restaurant management',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'fleet-management',
    name: 'Fleet Management',
    icon: '🚚',
    description: 'Vehicle tracking, driver behavior, fuel management, maintenance scheduling',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'iot',
    name: 'IoT',
    icon: '📡',
    description: 'Device registry, shadows, firmware updates, MQTT broker, telemetry',
    required: false,
    fileCount: 6,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'smart-home',
    name: 'Smart Home',
    icon: '🏡',
    description: 'Alexa skills, Google Actions, HomeKit, automation rules',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'agritech',
    name: 'AgriTech',
    icon: '🌾',
    description: 'Crop monitoring, soil analysis, irrigation control, weather integration',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'supply-chain',
    name: 'Supply Chain',
    icon: '📦',
    description: 'Inventory management, demand forecasting, shipment tracking, warehouse management',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'edge',
    name: 'Edge Computing',
    icon: '🌐',
    description: 'Cloudflare Workers, Vercel Edge, Deno Deploy, Akamai, Fastly',
    required: false,
    fileCount: 6,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'edge-ai',
    name: 'Edge AI',
    icon: '🧠',
    description: 'On-device inference, model optimization, federated learning',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'algo-trading',
    name: 'Algorithmic Trading',
    icon: '📈',
    description: 'Trading strategies, backtesting, market data feed, risk management',
    required: false,
    fileCount: 5,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'robo-advisory',
    name: 'Robo-Advisory',
    icon: '🤖',
    description: 'Portfolio optimization, rebalancing, tax-loss harvesting',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'credit-scoring',
    name: 'Credit Scoring',
    icon: '💳',
    description: 'ML scoring models, risk assessment, alternative data',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'fraud-detection',
    name: 'Fraud Detection',
    icon: '🚨',
    description: 'Transaction monitoring, anomaly detection, pattern recognition',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'regtech',
    name: 'RegTech',
    icon: '⚖️',
    description: 'Compliance automation, regulatory changes, reporting engine',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'insurtech',
    name: 'InsurTech',
    icon: '🏥',
    description: 'Claims processing, risk assessment, underwriting automation',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'bnpl',
    name: 'Buy Now Pay Later',
    icon: '💸',
    description: 'Creditworthiness, installment calculation, payment scheduling',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'crypto-exchange',
    name: 'Crypto Exchange',
    icon: '💱',
    description: 'Order matching, liquidity management, cold wallet integration',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'cross-border-payments',
    name: 'Cross-Border Payments',
    icon: '🌍',
    description: 'FX conversion, SWIFT integration, compliance checks',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'micro-lending',
    name: 'Micro-Lending',
    icon: '💰',
    description: 'Loan origination, credit decisioning, collection management',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },

  // Continue with more advanced categories...
  {
    key: 'property-valuation',
    name: 'Property Valuation',
    icon: '🏘️',
    description: 'Automated valuation, comparative analysis, market trends',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'smart-building',
    name: 'Smart Building',
    icon: '🏢',
    description: 'HVAC control, occupancy monitoring, energy optimization',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'tenant-management',
    name: 'Tenant Management',
    icon: '👥',
    description: 'Lease management, maintenance requests, rent collection',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'construction-mgmt',
    name: 'Construction Management',
    icon: '🏗️',
    description: 'Project scheduling, material tracking, progress monitoring',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'facility-management',
    name: 'Facility Management',
    icon: '🔧',
    description: 'Work order system, preventive maintenance, asset tracking',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'coworking',
    name: 'Coworking',
    icon: '🪑',
    description: 'Desk booking, access control, billing integration',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'real-estate-crm',
    name: 'Real Estate CRM',
    icon: '📊',
    description: 'Lead management, property matching, client communication',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'property-inspection',
    name: 'Property Inspection',
    icon: '🔍',
    description: 'Checklist builder, photo documentation, report generation',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'rental-marketplace',
    name: 'Rental Marketplace',
    icon: '🏠',
    description: 'Listing management, booking engine, review system',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'mortgage-processing',
    name: 'Mortgage Processing',
    icon: '🏦',
    description: 'Application workflow, document verification, underwriting support',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'precision-agriculture',
    name: 'Precision Agriculture',
    icon: '🚜',
    description: 'Soil monitoring, variable rate application, yield prediction',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'livestock',
    name: 'Livestock Management',
    icon: '🐄',
    description: 'Health monitoring, breeding management, feed optimization',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'hydroponics',
    name: 'Hydroponics',
    icon: '🌱',
    description: 'Nutrient management, pH monitoring, growth optimization',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'carbon-credits',
    name: 'Carbon Credits',
    icon: '🌍',
    description: 'Emission calculation, credit issuance, marketplace',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'renewable-energy',
    name: 'Renewable Energy',
    icon: '⚡',
    description: 'Solar forecasting, wind prediction, battery optimization',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'waste-management',
    name: 'Waste Management',
    icon: '♻️',
    description: 'Recycling tracking, route optimization, disposal compliance',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'water-quality',
    name: 'Water Quality',
    icon: '💧',
    description: 'Sensor integration, contamination detection, compliance reporting',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'environmental-compliance',
    name: 'Environmental Compliance',
    icon: '🌳',
    description: 'Emissions tracking, permit management, regulatory reporting',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'circular-economy',
    name: 'Circular Economy',
    icon: '🔄',
    description: 'Material recovery, product lifecycle, recycling marketplace',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'sustainable-supply',
    name: 'Sustainable Supply Chain',
    icon: '🌿',
    description: 'Carbon footprint, ethical sourcing, sustainability metrics',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'telemedicine',
    name: 'Telemedicine',
    icon: '👨‍⚕️',
    description: 'Video consultation, patient queue, prescription management',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'medical-imaging',
    name: 'Medical Imaging',
    icon: '🔬',
    description: 'DICOM processing, PACS integration, image analysis',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'clinical-decision',
    name: 'Clinical Decision Support',
    icon: '🩺',
    description: 'Diagnosis assistance, drug interaction, protocol recommendations',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'wearables',
    name: 'Wearable Devices',
    icon: '⌚',
    description: 'Fitness tracker, health monitoring, data aggregation',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'pharmacy',
    name: 'Pharmacy Management',
    icon: '💊',
    description: 'Drug database, inventory management, prescription filling',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'lims',
    name: 'LIMS',
    icon: '🧪',
    description: 'Experiment management, sample tracking, result analysis',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'lis',
    name: 'Laboratory Information System',
    icon: '🧪',
    description: 'Specimen tracking, result reporting, quality control',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'clinical-trials',
    name: 'Clinical Trials',
    icon: '📊',
    description: 'Participant enrollment, data collection, adverse event reporting',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'medical-billing',
    name: 'Medical Billing',
    icon: '💵',
    description: 'Coding systems, insurance claims, reimbursement',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'patient-portal',
    name: 'Patient Portal',
    icon: '👤',
    description: 'Appointment booking, medical records, messaging',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'population-health',
    name: 'Population Health',
    icon: '📈',
    description: 'Disease surveillance, risk stratification, health outcomes',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'mes',
    name: 'Manufacturing Execution System',
    icon: '🏭',
    description: 'Production scheduling, material tracking, quality control',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'predictive-maintenance',
    name: 'Predictive Maintenance',
    icon: '🔧',
    description: 'Failure prediction, sensor monitoring, maintenance scheduling',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'digital-twin-mfg',
    name: 'Digital Twin Manufacturing',
    icon: '👥',
    description: 'Process simulation, optimization, what-if analysis',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'qms',
    name: 'Quality Management System',
    icon: '✅',
    description: 'Non-conformance, corrective action, audit management',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'supply-chain-visibility',
    name: 'Supply Chain Visibility',
    icon: '👁️',
    description: 'Track & trace, logistics integration, supplier management',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'asset-management',
    name: 'Asset Management',
    icon: '📦',
    description: 'Equipment tracking, maintenance history, depreciation',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'energy-management',
    name: 'Energy Management',
    icon: '⚡',
    description: 'Consumption monitoring, optimization, renewable integration',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'warehouse-automation',
    name: 'Warehouse Automation',
    icon: '🤖',
    description: 'Robot control, picking optimization, inventory tracking',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'production-optimization',
    name: 'Production Optimization',
    icon: '📊',
    description: 'Bottleneck analysis, resource allocation, throughput improvement',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'safety-management',
    name: 'Safety Management',
    icon: '🦺',
    description: 'Incident reporting, risk assessment, compliance tracking',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'telemetry',
    name: 'Telemetry',
    icon: '📡',
    description: 'Performance tracking, crash reporting, heatmaps',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'game-analytics',
    name: 'Game Analytics',
    icon: '📊',
    description: 'Player metrics, retention analysis, monetization tracking',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'game-state',
    name: 'Game State',
    icon: '💾',
    description: 'Save system, cloud saves, conflict resolution',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'multiplayer-sync',
    name: 'Multiplayer Sync',
    icon: '🔄',
    description: 'State replication, client prediction, lag compensation',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'guilds',
    name: 'Guilds',
    icon: '👥',
    description: 'Creation, hierarchy, permissions',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'tournaments',
    name: 'Tournaments',
    icon: '🏆',
    description: 'Bracket generation, scheduling, prize distribution',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'seasons',
    name: 'Seasons',
    icon: '📅',
    description: 'Battle pass, event scheduling, seasonal rewards',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'virtual-economy',
    name: 'Virtual Economy',
    icon: '💰',
    description: 'Currency management, marketplace, trading system',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'anti-cheat',
    name: 'Anti-Cheat',
    icon: '🛡️',
    description: 'Client verification, behavior analysis, statistical detection',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },
  {
    key: 'esports',
    name: 'Esports',
    icon: '🎮',
    description: 'Replay system, spectator mode, statistics API',
    required: false,
    fileCount: 4,
    level: LEVELS.ADVANCED,
  },

  // ===== EXPERT LEVEL (68 categories) =====
  {
    key: 'metaverse',
    name: 'Metaverse',
    icon: '🌐',
    description: 'Virtual worlds, avatar management, NFT wearables, spatial audio',
    required: false,
    fileCount: 5,
    level: LEVELS.EXPERT,
  },
  {
    key: 'quantum',
    name: 'Quantum Computing',
    icon: '⚛️',
    description: 'Qiskit integration, quantum algorithms, quantum simulation',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'quantum-crypto',
    name: 'Quantum Cryptography',
    icon: '🔐',
    description: 'Post-quantum encryption, QKD protocols',
    required: false,
    fileCount: 3,
    level: LEVELS.EXPERT,
  },
  {
    key: 'digital-twins',
    name: 'Digital Twins',
    icon: '👥',
    description: 'Twin creation, real-time sync, simulation',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'bci',
    name: 'Brain-Computer Interface',
    icon: '🧠',
    description: 'EEG processing, signal interpretation, neural feedback',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'defi',
    name: 'DeFi',
    icon: '🏦',
    description: 'Smart contracts, liquidity pools, staking, yield farming, DAO governance',
    required: false,
    fileCount: 6,
    level: LEVELS.EXPERT,
  },
  {
    key: 'nft-marketplace',
    name: 'NFT Marketplace',
    icon: '🖼️',
    description: 'Minting, trading, royalties, metadata storage',
    required: false,
    fileCount: 5,
    level: LEVELS.EXPERT,
  },
  {
    key: 'crypto-wallets',
    name: 'Crypto Wallets',
    icon: '💼',
    description: 'Wallet creation, multi-sig, transaction signing, hardware wallet',
    required: false,
    fileCount: 5,
    level: LEVELS.EXPERT,
  },
  {
    key: 'bridges',
    name: 'Blockchain Bridges',
    icon: '🌉',
    description: 'Ethereum-Polygon, Layer 2 bridges, wrapped tokens',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'oracles',
    name: 'Blockchain Oracles',
    icon: '🔮',
    description: 'Chainlink, Band Protocol, API3',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'tokenomics',
    name: 'Tokenomics',
    icon: '💎',
    description: 'Token distribution, vesting, burning',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'did',
    name: 'Decentralized Identity',
    icon: '🆔',
    description: 'DID resolution, verifiable credentials, identity wallet',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'blockchain-indexing',
    name: 'Blockchain Indexing',
    icon: '📊',
    description: 'The Graph, Moralis, Alchemy indexer, custom indexer',
    required: false,
    fileCount: 5,
    level: LEVELS.EXPERT,
  },
  {
    key: 'ipfs',
    name: 'IPFS',
    icon: '📦',
    description: 'Distributed storage, file pinning, gateway',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'decentralized-storage',
    name: 'Decentralized Storage',
    icon: '💾',
    description: 'Arweave, Filecoin, Storj',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'contract-auditing',
    name: 'Contract Auditing',
    icon: '🔍',
    description: 'Static analysis, vulnerability detection, gas optimization',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'drm-advanced',
    name: 'DRM Advanced',
    icon: '🔐',
    description: 'Widevine, PlayReady, FairPlay integration',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'autonomous-vehicle',
    name: 'Autonomous Vehicles',
    icon: '🚗',
    description: 'Sensor fusion, object detection, path planning',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'connected-car',
    name: 'Connected Car',
    icon: '🚙',
    description: 'Vehicle telemetry, OTA updates, remote diagnostics',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'ev-management',
    name: 'EV Management',
    icon: '🔋',
    description: 'Charging stations, battery monitoring, range calculation',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'ride-sharing',
    name: 'Ride Sharing',
    icon: '🚕',
    description: 'Driver matching, route optimization, surge pricing',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'bioinformatics',
    name: 'Bioinformatics',
    icon: '🧬',
    description: 'Genome sequencing, protein analysis, phylogenetic trees',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'biometrics',
    name: 'Biometrics',
    icon: '👆',
    description: 'Fingerprint, facial recognition, iris scan, voice recognition',
    required: false,
    fileCount: 5,
    level: LEVELS.EXPERT,
  },
  {
    key: 'astronomy',
    name: 'Astronomy',
    icon: '🔭',
    description: 'Celestial object detection, image processing, data calibration',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'particle-physics',
    name: 'Particle Physics',
    icon: '⚛️',
    description: 'Collision data analysis, event reconstruction, simulation',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'climate-modeling',
    name: 'Climate Modeling',
    icon: '🌍',
    description: 'Weather simulation, climate prediction, scenario analysis',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'nuclear-facility',
    name: 'Nuclear Facility',
    icon: '☢️',
    description: 'Radiation monitoring, safety protocols',
    required: false,
    fileCount: 3,
    level: LEVELS.EXPERT,
  },
  {
    key: 'space-mission',
    name: 'Space Mission',
    icon: '🚀',
    description: 'Telemetry processing, trajectory calculation',
    required: false,
    fileCount: 3,
    level: LEVELS.EXPERT,
  },
  {
    key: 'submarine-nav',
    name: 'Submarine Navigation',
    icon: '🚢',
    description: 'Sonar processing, underwater communications',
    required: false,
    fileCount: 3,
    level: LEVELS.EXPERT,
  },
  {
    key: 'dna-storage',
    name: 'DNA Data Storage',
    icon: '🧬',
    description: 'Nucleotide encoding, sequencing retrieval',
    required: false,
    fileCount: 3,
    level: LEVELS.EXPERT,
  },
  {
    key: '5g',
    name: '5G',
    icon: '📶',
    description: 'Network slicing, edge computing, ultra-low latency',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'interactive-video',
    name: 'Interactive Video',
    icon: '🎬',
    description: 'Branching scenarios, clickable hotspots, quiz integration',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'e-government',
    name: 'E-Government',
    icon: '🏛️',
    description: 'Tax filing, license renewal, permit applications',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'voting-systems',
    name: 'Voting Systems',
    icon: '🗳️',
    description: 'Electronic voting, ballot validation, result tabulation',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'citizen-engagement',
    name: 'Citizen Engagement',
    icon: '👥',
    description: 'Feedback portal, petition system, town hall digital',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'public-safety',
    name: 'Public Safety',
    icon: '🚨',
    description: 'Crime prediction, hotspot analysis, pattern detection',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'emergency-dispatch',
    name: 'Emergency Dispatch',
    icon: '🚑',
    description: 'Priority queue, location tracking, resource allocation',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'search-rescue',
    name: 'Search and Rescue',
    icon: '⛑️',
    description: 'Team coordination, equipment tracking, coordinate management',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'fire-detection',
    name: 'Fire Detection',
    icon: '🔥',
    description: 'Smoke sensor integration, heat mapping, evacuation routing',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'disaster-management',
    name: 'Disaster Management',
    icon: '🌪️',
    description: 'Alert system, evacuation planning, resource coordination',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'traffic-management',
    name: 'Traffic Management',
    icon: '🚦',
    description: 'Congestion detection, signal optimization, incident detection',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'transit-planning',
    name: 'Transit Planning',
    icon: '🚇',
    description: 'Route optimization, demand forecasting, service scheduling',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'public-records',
    name: 'Public Records',
    icon: '📜',
    description: 'Document archival, FOIA requests, redaction engine',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'permits-licensing',
    name: 'Permits and Licensing',
    icon: '📋',
    description: 'Application workflow, inspection scheduling, renewal notifications',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'social-services',
    name: 'Social Services',
    icon: '🤝',
    description: 'Benefit eligibility, case worker management, resource allocation',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'immigration',
    name: 'Immigration',
    icon: '🛂',
    description: 'Application processing, document verification, status tracking',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'procurement',
    name: 'Procurement',
    icon: '📦',
    description: 'Bid management, contract lifecycle, vendor evaluation',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'grant-management',
    name: 'Grant Management',
    icon: '💰',
    description: 'Proposal submission, budget tracking, reporting compliance',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'research-data',
    name: 'Research Data',
    icon: '🔬',
    description: 'Data repository, version control, collaboration tools',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'peer-review',
    name: 'Peer Review',
    icon: '📝',
    description: 'Manuscript submission, reviewer assignment, revision tracking',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'scientific-collaboration',
    name: 'Scientific Collaboration',
    icon: '👥',
    description: 'Data sharing, co-authoring, shared workspaces',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'chemical-inventory',
    name: 'Chemical Inventory',
    icon: '🧪',
    description: 'Hazard tracking, safety data sheets, disposal management',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'equipment-rental',
    name: 'Equipment Rental',
    icon: '🔧',
    description: 'Booking system, inventory management, maintenance tracking',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'case-management',
    name: 'Case Management',
    icon: '📁',
    description: 'Case tracking, document management, workflow automation',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'medical-emergency',
    name: 'Medical Emergency',
    icon: '🚑',
    description: 'Patient triage, ambulance dispatch, hospital routing',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'panic-button',
    name: 'Panic Button',
    icon: '🆘',
    description: 'Instant alert, location broadcast, escalation protocol',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'incident-reporting',
    name: 'Incident Reporting',
    icon: '📝',
    description: 'Report submission, photo documentation, follow-up tracking',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'crisis-communication',
    name: 'Crisis Communication',
    icon: '📢',
    description: 'Mass notification, multi-channel alerts, acknowledgment tracking',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'weather-alerts',
    name: 'Weather Alerts',
    icon: '⛈️',
    description: 'Severe weather detection, geo-targeted alerts, multi-language support',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'sustainability',
    name: 'Sustainability',
    icon: '🌱',
    description: 'Carbon offset, emission calculation, energy monitoring',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'nutrition',
    name: 'Nutrition',
    icon: '🥗',
    description: 'Calorie counting, macro tracking, meal planning',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'workout-planning',
    name: 'Workout Planning',
    icon: '💪',
    description: 'Exercise database, personalized routines, progression tracking',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'meditation',
    name: 'Meditation',
    icon: '🧘',
    description: 'Guided sessions, progress tracking, reminder system',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'sleep-tracking',
    name: 'Sleep Tracking',
    icon: '😴',
    description: 'Sleep stages, quality analysis, recommendations',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'mental-health',
    name: 'Mental Health',
    icon: '🧠',
    description: 'Mood tracking, therapy scheduling, crisis intervention',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'supplements',
    name: 'Supplements',
    icon: '💊',
    description: 'Dosage tracking, interaction checker, reorder reminders',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'trainer-matching',
    name: 'Trainer Matching',
    icon: '👟',
    description: 'Trainer profiles, session scheduling, progress reports',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'wellness-challenges',
    name: 'Wellness Challenges',
    icon: '🎯',
    description: 'Challenge creation, leaderboards, progress tracking',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
  {
    key: 'corporate-wellness',
    name: 'Corporate Wellness',
    icon: '🏢',
    description: 'Employee challenges, wellness metrics, incentive management',
    required: false,
    fileCount: 4,
    level: LEVELS.EXPERT,
  },
];
// Export functions
export function getAllCategories() {
  return folderCategories;
}

export function getAllFolders() {
  return folderCategories.map(cat => cat.key);
}

export function getCategoriesByLevel(level) {
  return folderCategories.filter(cat => cat.level === level);
}

export function getRequiredCategories() {
  return folderCategories.filter(cat => cat.required);
}

export function getCategoryByKey(key) {
  return folderCategories.find(cat => cat.key === key);
}

export function getFoldersByLevel(level) {
  return folderCategories
    .filter(cat => cat.level === level)
    .map(cat => cat.key);
}

export const TOTAL_CATEGORIES = folderCategories.length;